In [1]:
import pandas as pd

In [12]:
df=pd.read_csv("C:/Users/Ibscai06.DGVC-MCA/padmapriya/iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width           class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           NaN          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  149 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  146 non-null    float64
 3   petal_width   149 non-null    float64
 4   class         149 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [18]:
df.isnull()

     sepal_length  sepal_width  petal_length  petal_width  class
0           False        False         False        False  False
1           False        False         False        False  False
2           False        False         False        False  False
3           False        False         False        False  False
4           False        False         False        False  False
..            ...          ...           ...          ...    ...
145         False        False         False        False  False
146         False        False         False        False  False
147         False        False          True        False  False
148         False        False         False        False  False
149         False        False         False        False  False

[150 rows x 5 columns]

In [19]:
df.isnull().sum()

sepal_length    1
sepal_width     0
petal_length    4
petal_width     1
class           1
dtype: int64

In [20]:
df['sepal_length']=df['sepal_length'].fillna(0)

In [21]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    4
petal_width     1
class           1
dtype: int64

In [22]:
mn=df['sepal_width'].mean()
mn

np.float64(3.057718120805369)

In [23]:
df['sepal_width']=df['sepal_width'].fillna(mn)

In [24]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    4
petal_width     1
class           1
dtype: int64

In [33]:
md=df['petal_width'].median()
md

1.3

In [39]:
df['petal_width']=df['petal_width'].fillna(md)

In [40]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    4
petal_width     0
class           1
dtype: int64

In [44]:
mo=df['petal_length'].mode()[0]
mo

np.float64(1.5)

In [45]:
df['petal_length']=df['petal_length'].fillna(mo)

In [46]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           1
dtype: int64

In [49]:
df['class']=df['class'].ffill()
df['class']=df['class'].bfill()
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64